server:
  port: 8080
database:
  url: jdbc:mysql://localhost:3306/specialty?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
  username: root
  password: kindy0916
spring:
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      enabled: true
  redis:
    #host: 172.17.240.99
    host: 47.98.128.88
    port: 6379
    database: 0
    password: sht123
    timeout: 5000
  jpa:
    show-sql: true
    hibernate:
      #create-drop
      ddl-auto: create-drop
