server:
  port: 8890
database:
  url: jdbc:mysql://47.98.128.88:3306/specialty?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: root
  password: kindy0916
spring:
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      enabled: true
  redis:
    host: 47.98.128.88
    port: 6379
    database: 0
    password: sht123
    timeout: 5000
  jpa:
    show-sql: false
    hibernate:
      #create-drop
      ddl-auto: update
