server:
  port: 6789
database:
  url: jdbc:mysql://47.98.128.88:3306/specialty?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: root
  password: kindy0916
spring:
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      enabled: true
  redis:
    #host: 172.17.240.99
    host: 47.98.128.88
    port: 6379
    database: 0
    password: sht123
    timeout: 5000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  jackson:
    default-property-inclusion: non_null
WX_DATA:
  appid: wx72280998498b78c9
  secret: e3198aacefab2c8b8684ea8573dc94bd
  grant_type: authorization_code
