spring:
  datasource:
    url: ENC(fXtcBfq64N3j1gvo0ZWgt4q7F34WwdEvWvjWw5K8HFgjU2h9JRWvpUaNoWmk+4qYWwWNJ0EPTuEIA/gWyIB5dPvHsxkHyGgvSsnQsjPrQCKOzjgoXjuhu8biiR2K07JyPakFxwt/nNsAKwtxFTcWBBNlR/0gUg9uRhe77Lvs5SwkbjkNaw2gMg==)
    username: ENC(0XAQhNsW5HAM6wajkcPgPQ==)
    password: ENC(2nsnZRQP+OYw+h5bnZt/fclV7aSYCi8x)
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ENC(Igwk57Nx5VSZ/uwywgszhZsFxmqw687s)
    port: 6379
    database: 0
    password: ENC(6u+uxPExCZ3TPUpD6C1qOQ==)
    timeout: 6000
    lettuce:
      pool:
        max-wait: -1
        max-idle: 8
        min-idle: 0
        max-active: 50
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapping/*.xml
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger
  try-host: http://localhost:${server.port}
