spring:
  datasource:
    url: ENC(mxceYq69oKooRhaDDCvhTKuEygNaGhNeG12BGQS5x39PqGNRIwfaNx70Ev7EtGnlrwsYQPw3mE4075mk4D6DJf/ftttuFkXaziShmzdyZN0z/Aqw6q21kIu+68A49j3N8q0LgOozw2PQ9jSKe18t7pDQFx7atThb4/qxVYDTdnYjeJKEWAeijA==)
    username: ENC(2Io83MWwLR/etZSrMIVNMw==)
    password: ENC(SU6acVIzxPtmSHKoZDnC2BcrFIfRFrZJ)
    #使用阿里巴巴Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ENC(jzqMWGCFmvFds15TpClclJz1qJhUZYzQ)
    port: 6379
    database: 0
    password: ENC(6u+uxPExCZ3TPUpD6C1qOQ==)
    timeout: 5000
mybatis:
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印sql语句包括查询结果
    map-underscore-to-camel-case: true #下划线转驼峰配置
